output_storage_path: mlops_timeseries_frameworktr
target_columns: sales
feature_columns: family

env: dev
experiment_name: /Shared/experiments
input_data:
  file_path: "/timeseries_storesales_oil.csv"

Arima_order:
  p: 2
  d: 0
  q: 1

output_data:
  preprocessed: preprocssed_data.csv
  resutl_data: result.csv

key_vault: kv-shs-az-eus-mlops-npd