trigger: none

variables:
- group: azure-blob

pool:
  name: 'BD-IAC-Pool-Linux'

stages:
- stage: Build
  displayName: 'Build and Deploy'
  jobs:
  - job: AddSecrets
    displayName: 'Add Secrets to Key Vault'
    steps:
    - task: AzureCLI@2
      displayName: 'Set Key Vault Secret'
      inputs:
        azureSubscription: 'TGS-MLOPS-DEV'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az keyvault secret set --name "AZURE-CONNECTION-STRING" --vault-name "kv-shs-az-eus-mlops-npd" --value "$(AZURE-CONNECTION-STRING)"
      env:
        AZURE_CONNECTION_STRING: $(AZURE-CONNECTION-STRING)